### ISSUE TITLE
Cannot resolve reference to bean 'solrServer'

### ISSUE THREAD

**Issue by anmiralles** [christophstrobl/spring-data-solr-showcase#1]
Hi Chris, I'm obtaining an error when running "mvn tomcat7:run". The solr server is up.

Información: Initializing Spring root WebApplicationContext
feb 13, 2014 12:19:11 PM org.apache.catalina.core.StandardContext listenerStart
Grave: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'productServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.data.solr.showcase.product.ProductServiceImpl.setProductRepository(org.springframework.data.solr.showcase.product.ProductRepository); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'productRepository': Cannot resolve reference to bean 'solrServer' while setting bean property 'solrServer'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'solrServer' is defined
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:292)

Could you please tell me how to solve this?

Thanks in advanced.

**Comment by christophstrobl** [comment]
Hi,
oh sorry about that, seems recent changes in spring-data-solr require `solrServer` to be present. 

Please change `SolrConfig` for now - I'll check the `SolrRepositoryConfigExtension`. 

``` java
    @Bean
    public SolrServer solrServer() throws MalformedURLException, IllegalStateException {
        return new HttpSolrServer(environment.getRequiredProperty(PROPERTY_NAME_SOLR_SERVER_URL));
    }

    @Bean
    public SolrServerFactory solrServerFactory() throws MalformedURLException, IllegalStateException {
        return new MulticoreSolrServerFactory(solrServer());
    }

    @Bean
    public SolrTemplate solrTemplate() throws Exception {
        SolrTemplate solrTemplate = new SolrTemplate(solrServerFactory());
        solrTemplate.setSolrCore("collection1");
        return solrTemplate;
    }

```

**Comment by christophstrobl** [comment]
@anmiralles Fixed the issue in [cd005f14](https://github.com/spring-projects/spring-data-solr/commit/cd005f1465bd7c51e3434f3a74815597f5221fc3). So the sample should be fine again.

Let me know if you still experience troubles.

**Comment by anmiralles** [comment]
Hi christoph,

still having problems. This time:

GRAVE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerAdapter' defined in class org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.requestMappingHandlerAdapter()] threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/hateoas/TemplateVariables

Thanks for helping ;)

**Comment by christophstrobl** [comment]
@anmiralles fixed version dependencies for spring-core, spring-hateoas and spring-data-solr to use the latest releases. Smoke test with solr 4.7 worked fine. Sorry for the inconvenience, should not have used snapshots in first place.

**Comment by anmiralles** [comment]
Fixed!!!

Thanks a lot Christoph ;)

**Comment by christophstrobl** [comment]
@anmiralles great! thanks for letting me know.

**Comment by Praveenmail2him** [comment]
Hi Chris, 
I'm trying to work with solr 5.5 version with java configuration. SolrServer seems to be depreciated. can you please let me know how can it achieved using embedded Solr Server?

**Comment by Systemmanic** [comment]
@Praveenmail2him Use `SolrClient` instead.

**Comment by christophstrobl** [comment]
there's also a branch using latest spring-boot and Solr 5. See [/tree/upgrade-to-spring-boot-1.4.0.M3](https://github.com/christophstrobl/spring-data-solr-showcase/tree/upgrade-to-spring-boot-1.4.0.M3)

**Comment by manjunathjain** [comment]
Hi @christophstrobl, I have a scenario where I want to read data from 2 different Solr URLs to check the differences in data. How can I achieve that.

**Comment by satya-sovan** [comment]
Hi @christophstrobl ,I have created the xml configuration I am getting below error
	
	
	<solr:solr-server id="solrServer"  url="http://localhost:8984/solr/ThreadBlog"/>
	
	
	
	<bean id="credentials" class="org.apache.http.auth.UsernamePasswordCredentials">
    	<constructor-arg index="0" type="java.lang.String" value="solr"/>
    	<constructor-arg index="1" type="java.lang.String" value="SolrRocks"></constructor-arg>
	</bean>
	
	
	<bean id="solrServerFactory" class="org.springframework.data.solr.server.SolrServerFactory">
		<constructor-arg index="0" ref="solrServer"/>
		<constructor-arg  name="core">
		<null/>
		
		</constructor-arg>
		
		<constructor-arg index="1" ref="credentials"/>
		<constructor-arg  type="java.lang.String" value="BASIC"/>	
	
	</bean>
	
	
	
	<bean id="solrTemplate"
		class="org.springframework.data.solr.core.SolrTemplate">
		<constructor-arg index="0" ref="solrServerFactory" />
	</bean>


Cannot resolve reference to bean 'solrServerFactory' while setting constructor argument
